version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  server:
    build: ./app
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    env_file:
      - ${DOCKER_ENV_FILE:-./app/.env}
    depends_on:
      - db

volumes:
  postgres_data:
